users:
  - NikolayZ
debug: true
development: true
key: NTI1MTk0MTA5MDE1ODE4Mjgx.DvzFKQ.h3R4Fyoc2R_K6qxTogOTp82s5Rk
command-prefix: $
SpideyBot:
  branch: 'develop'
  color: test-result-color
  channel: 'questions'
db-connection:
  driver: 'mysql'
  username: dbuser
  password: dbpassword
  port: 3306
  host: localhost
  database: soerbot