# $leaderboard-add command settings

name: 'leaderboard-add'
description: 'Добавляет награду участнику'
storeJSONFile: '/../Store/leaderboard.json'
allowRoles:
  - 'product owner'
  - 'куратор'
args:
  - key: 'name'
    label: 'name'
    prompt: 'Введите имя пользователя'
    type: 'user'
  - key: 'emoji'
    label: 'emoji'
    prompt: 'Какую награду добавить?'
    type: 'reward'
rewardsPoints:
  ⭐: 1
  🏅: 5


